[project]
name = "10j"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12.3"
dependencies = [
    "click==8.1.8",
    "mypy==1.15.0",
    "packaging==24.2",
    "ruff==0.11.7",
]
